### ----- BASE PARAMS ----- ###
CORRECTED_DIRPATH: "quast_correct_input"

min_contig: 500

### ----- TEST PARAMS ----- ###

threads: 4

is_prokaryote: True
is_fungus: False

### ----- MODULES ----- ###

gene_prediction: False

busco: False

kmer_analysis: False

### ----- TEST FILES ----- ###
samples:
    A: test_data/contigs_1.fasta
    B: test_data/contigs_2.fasta

reference:
    test_data/reference.fasta

output_dir:
    quast_test_output

features_files:
    - test_data/genes.gff
    - test_data/operons.bed

features:
    - gene
    - operon

reads_files:
    - test_data/reads1.fastq.gz,test_data/reads2.fastq.gz

reads_types:
    - pe

search_sv: True