### ----- BASE PARAMS ----- ###
CORRECTED_DIRPATH: "quast_correct_input"

min_contig: 500

### ----- TEST PARAMS ----- ###

threads: 4

is_prokariote: True

gene_prediction: True

### ----- TEST FILES ----- ###
samples:
    A: test_data/contigs_1.fasta
    B: test_data/contigs_2.fasta

reference:
    test_data/reference.fasta

output_dir:
    quast_test_output

features:
    - test_data/genes.gff
    - test_data/operons.bed

features_type:
    - gene
    - operon